name: Cantarero
favicon: null
layout_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#272623'
    - '#c4e7ff'
    - '#817168'
    - '#86b6e4'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose:
  - name: awareness
    item: 96ef5e4f-f183-4080-9d00-a254cf4389b4
    url: null
