name: Cantarero
favicon: null
layout_spectrum: 0.26832
typography_spectrum: 0.13931
title: Alejandro Cantarero
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5eff1'
    - '#000000'
    - '#b5847f'
    - '#51544b'
    - '#fdb975'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: 96ef5e4f-f183-4080-9d00-a254cf4389b4
    url: null
